name: Deploy branch to XDN

on: push

jobs:
  deploy-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Next.js Example - Install modules
        run: npm ci
        working-directory: ./xdn-next-example
      - name: Next.js Example - Deploy to XDN
        run: npm run xdn:deploy -- ${{'--branch=$BRANCH_NAME' || ''}} --token=$xdn_deploy_token ${{env.BRANCH_NAME != 'main' && '--environment=staging' || ''}}
        env:
          xdn_deploy_token: ${{secrets.XDN_NEXT_DEPLOY_TOKEN}}
        working-directory: ./xdn-next-example
      - name: Sapper Example - Install modules
        run: npm ci
        working-directory: ./xdn-sapper-example
      - name: Sapper Example - Deploy to XDN
        run: npm run xdn:deploy -- ${{'--branch=$BRANCH_NAME' || ''}} --token=$xdn_deploy_token ${{env.BRANCH_NAME != 'main' && '--environment=staging' || ''}}
        env:
          xdn_deploy_token: ${{secrets.XDN_SAPPER_DEPLOY_TOKEN}}
        working-directory: ./xdn-sapper-example
      - name: NuxtJS Example - Install modules
        run: npm ci
        working-directory: ./xdn-nuxt-example
      - name: NuxtJS Example - Deploy to XDN
        run: npm run xdn:deploy -- ${{'--branch=$BRANCH_NAME' || ''}} --token=$xdn_deploy_token ${{env.BRANCH_NAME != 'main' && '--environment=staging' || ''}}
        env:
          xdn_deploy_token: ${{secrets.XDN_NUXT_DEPLOY_TOKEN}}
        working-directory: ./xdn-nuxt-example
      - name: Spartacus Example - Install modules
        run: npm ci
        working-directory: ./xdn-spartacus-example
      - name: Spartacus Example - Deploy to XDN
        run: npm run xdn:deploy -- ${{'--branch=$BRANCH_NAME' || ''}} --token=$xdn_deploy_token ${{env.BRANCH_NAME != 'main' && '--environment=staging' || ''}}
        env:
          xdn_deploy_token: ${{secrets.XDN_SPARTACUS_DEPLOY_TOKEN}}
        working-directory: ./xdn-spartacus-example
      - name: Vue Storefront Example - Deploy to XDN
        run: npm run xdn:deploy -- ${{'--branch=$BRANCH_NAME' || ''}} --token=$xdn_deploy_token ${{env.BRANCH_NAME != 'main' && '--environment=staging' || ''}}
        env:
          xdn_deploy_token: ${{secrets.XDN_VSF_DEPLOY_TOKEN}}
        working-directory: ./xdn-vue-storefront-example
